
package webservice.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonCreatorImplService", targetNamespace = "http://ws.webservice/", wsdlLocation = "http://localhost:12345/ws/person?wsdl")
public class PersonCreatorImplService
    extends Service
{

    private final static URL PERSONCREATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONCREATORIMPLSERVICE_EXCEPTION;
    private final static QName PERSONCREATORIMPLSERVICE_QNAME = new QName("http://ws.webservice/", "PersonCreatorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:12345/ws/person?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONCREATORIMPLSERVICE_WSDL_LOCATION = url;
        PERSONCREATORIMPLSERVICE_EXCEPTION = e;
    }

    public PersonCreatorImplService() {
        super(__getWsdlLocation(), PERSONCREATORIMPLSERVICE_QNAME);
    }

    public PersonCreatorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONCREATORIMPLSERVICE_QNAME, features);
    }

    public PersonCreatorImplService(URL wsdlLocation) {
        super(wsdlLocation, PERSONCREATORIMPLSERVICE_QNAME);
    }

    public PersonCreatorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONCREATORIMPLSERVICE_QNAME, features);
    }

    public PersonCreatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonCreatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonCreator
     */
    @WebEndpoint(name = "PersonCreatorImplPort")
    public PersonCreator getPersonCreatorImplPort() {
        return super.getPort(new QName("http://ws.webservice/", "PersonCreatorImplPort"), PersonCreator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonCreator
     */
    @WebEndpoint(name = "PersonCreatorImplPort")
    public PersonCreator getPersonCreatorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.webservice/", "PersonCreatorImplPort"), PersonCreator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONCREATORIMPLSERVICE_EXCEPTION!= null) {
            throw PERSONCREATORIMPLSERVICE_EXCEPTION;
        }
        return PERSONCREATORIMPLSERVICE_WSDL_LOCATION;
    }

}
